#!/usr/bin/env python3
"""
auto-handoff.py - Claude Code Stop hook
Fires when a Claude Code session ends.
Generates HANDOFF automatically from Auto Memory + git state.
Saves to: Journal (Dropbox, append) + docs/HANDOFF (git repo, overwrite)
"""
import os
import sys
import subprocess
import fcntl
import time
from datetime import datetime
from pathlib import Path

# Paths
PROJECT_DIR = os.environ.get("CLAUDE_PROJECT_DIR", os.path.expanduser("~/claude-telegram-bot"))
MEMORY_DIR = os.path.expanduser("~/.claude/projects/-Users-daijiromatsuokam1-claude-telegram-bot/memory")
JOURNAL_DIR = os.path.expanduser("~/Machinelab Dropbox/Matsuoka Daijiro/JARVIS-Journal")
ENV_FILE = os.path.join(PROJECT_DIR, ".env")
LOG_FILE = "/tmp/auto-handoff.log"
LOCK_FILE = "/tmp/auto-handoff.lock"

def log(msg):
    with open(LOG_FILE, "a") as f:
        f.write(f"[{datetime.now().strftime('%H:%M:%S')}] {msg}\n")

def read_file(path, default=""):
    try:
        return Path(path).read_text()
    except Exception:
        return default

def run_cmd(cmd, cwd=None):
    try:
        r = subprocess.run(cmd, shell=True, capture_output=True, text=True, timeout=10, cwd=cwd)
        return r.stdout.strip()
    except Exception:
        return ""

def main():
    # Layer 1: Timestamp dedup - skip if ran within last 5 seconds
    STAMP_FILE = "/tmp/auto-handoff.stamp"
    try:
        if os.path.exists(STAMP_FILE):
            age = time.time() - os.path.getmtime(STAMP_FILE)
            if age < 5:
                return  # Another instance just ran
    except Exception:
        pass

    # Layer 2: fcntl lock - prevent concurrent execution
    lock_fd = open(LOCK_FILE, "w")
    try:
        fcntl.flock(lock_fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
    except OSError:
        return  # Another instance running
    try:
        # Write stamp BEFORE work (prevents second process from starting)
        Path(STAMP_FILE).touch()
        _run()
    finally:
        fcntl.flock(lock_fd, fcntl.LOCK_UN)
        lock_fd.close()

def _run():
    log("Stop hook fired")
    now = datetime.now()
    date_str = now.strftime("%Y-%m-%d")
    time_str = now.strftime("%H:%M")

    # Read memory files
    memory_md = read_file(os.path.join(MEMORY_DIR, "MEMORY.md"))
    arch_md = read_file(os.path.join(MEMORY_DIR, "architecture.md"))
    lessons_md = read_file(os.path.join(MEMORY_DIR, "lessons.md"))
    tasks_md = read_file(os.path.join(MEMORY_DIR, "task-state.md"))

    # Git state
    git_status = run_cmd("git status --short", cwd=PROJECT_DIR)
    git_branch = run_cmd("git branch --show-current", cwd=PROJECT_DIR)
    git_log = run_cmd("git log --oneline -5", cwd=PROJECT_DIR)
    git_diff_stat = run_cmd("git diff --stat", cwd=PROJECT_DIR)

    # M1 state
    m1_state = read_file(os.path.join(PROJECT_DIR, "autonomous/state/M1.md"))

    # Build HANDOFF
    bt = chr(96) * 3  # backtick fence
    uncommitted = len(git_status.splitlines()) if git_status else 0
    diff_part = f"- Diff stats:\n{bt}\n{git_diff_stat}\n{bt}" if git_diff_stat else ""

    lines = [
        f"# Auto-HANDOFF {date_str} {time_str}",
        "*Generated by Stop hook (auto-handoff.py)*",
        "",
        "---",
        "",
        "## Git State",
        f"- Branch: {git_branch}",
        f"- Uncommitted: {uncommitted} files",
        bt,
        git_status or "(clean)",
        bt,
        "- Recent commits:",
        bt,
        git_log,
        bt,
        diff_part,
        "",
        "---",
        "",
        "## M1 State",
        bt,
        m1_state or "(not found)",
        bt,
        "",
        "---",
        "",
        "## Memory Snapshot",
        "",
        "### MEMORY.md",
        memory_md,
        "",
        "### Task State",
        tasks_md,
        "",
        "### Architecture Decisions",
        arch_md,
        "",
        "### Lessons Learned",
        lessons_md,
    ]
    handoff = "\n".join(lines)

    # 1. Save to Journal (Dropbox) - append (multiple sessions per day)
    os.makedirs(JOURNAL_DIR, exist_ok=True)
    journal_path = os.path.join(JOURNAL_DIR, f"auto-handoff-{date_str}.md")
    with open(journal_path, "a") as f:
        f.write(handoff + "\n\n---\n\n")
    log(f"Journal saved: {journal_path}")

    # 2. Save to docs/ (git repo) - overwrite (latest session wins)
    docs_dir = os.path.join(PROJECT_DIR, "docs")
    os.makedirs(docs_dir, exist_ok=True)
    docs_path = os.path.join(docs_dir, f"HANDOFF_{date_str}.md")
    with open(docs_path, "w") as f:
        f.write(handoff + "\n")
    log(f"docs/ saved: {docs_path}")

    # Sync memory -> croppy-notes
    sync_script = os.path.join(PROJECT_DIR, "scripts/memory-sync.sh")
    if os.path.exists(sync_script):
        run_cmd(f"bash {sync_script}")
        log("memory-sync executed")

    log("Done")

if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        log(f"ERROR: {e}")
        sys.exit(0)  # Always exit 0 - Stop hooks should not block
