#!/bin/bash
# generate-changelog.sh — Generate CHANGELOG.md from git log
# Groups commits by conventional commit prefix (feat/fix/chore/refactor/docs/test/style/perf)
# Usage: bash scripts/generate-changelog.sh > CHANGELOG.md
set -uo pipefail

cd "$(git rev-parse --show-toplevel)" 2>/dev/null || cd "$(dirname "$0")/.." || exit 1

# Get all commits, format: hash|date|subject
ALL_COMMITS=$(git log --format="%H|%ad|%s" --date=format:"%Y-%m-%d" 2>/dev/null)

if [ -z "$ALL_COMMITS" ]; then
  echo "# Changelog"
  echo ""
  echo "No commits found."
  exit 0
fi

echo "# Changelog"
echo ""
echo "> Auto-generated by generate-changelog.sh"
echo ""

# Collect unique dates in order
DATES=$(echo "$ALL_COMMITS" | awk -F'|' '{print $2}' | sort -ru)

for DATE in $DATES; do
  # Get commits for this date
  DATE_COMMITS=$(echo "$ALL_COMMITS" | awk -F'|' -v d="$DATE" '$2 == d {print $1 "|" $3}')
  [ -z "$DATE_COMMITS" ] && continue

  echo "## [$DATE]"
  echo ""

  # Group by prefix
  declare -A GROUPS
  GROUPS=()

  while IFS='|' read -r hash subject; do
    # Extract prefix (feat, fix, chore, refactor, docs, test, style, perf, ci, build, revert)
    prefix=$(echo "$subject" | sed -E 's/^(feat|fix|chore|refactor|docs|test|style|perf|ci|build|revert)(\(.+\))?!?:.*/\1/')
    if [ "$prefix" = "$subject" ]; then
      prefix="other"
    fi
    short_hash="${hash:0:7}"
    # Strip prefix from message
    msg=$(echo "$subject" | sed -E 's/^(feat|fix|chore|refactor|docs|test|style|perf|ci|build|revert)(\(.+\))?!?:\s*//')
    entry="- \`$short_hash\` $msg"
    GROUPS["$prefix"]="${GROUPS[$prefix]:-}$entry"$'\n'
  done <<< "$DATE_COMMITS"

  # Output in priority order
  for prefix in feat fix refactor perf chore docs test style ci build revert other; do
    if [ -n "${GROUPS[$prefix]:-}" ]; then
      case "$prefix" in
        feat)     label="### Features" ;;
        fix)      label="### Bug Fixes" ;;
        refactor) label="### Refactoring" ;;
        perf)     label="### Performance" ;;
        chore)    label="### Chores" ;;
        docs)     label="### Documentation" ;;
        test)     label="### Tests" ;;
        style)    label="### Style" ;;
        ci)       label="### CI/CD" ;;
        build)    label="### Build" ;;
        revert)   label="### Reverts" ;;
        other)    label="### Other" ;;
      esac
      echo "$label"
      echo ""
      echo -e "${GROUPS[$prefix]}"
    fi
  done

  unset GROUPS
done
