#!/bin/bash
# Reconcile a manufacturer's manual PDFs (Dropbox reference folder) against extracted text.
# Generalized from sync-keyence-manuals.sh to handle any maker (keyence / iai / oriental-motor / ...).
# Extracts NEW/changed PDFs, records a manifest, writes a human-readable STATUS.md.
#
# Usage:
#   sync-manuals.sh <maker>             # process new PDFs + refresh STATUS
#   sync-manuals.sh <maker> --status    # status only, do not extract
#   sync-manuals.sh <maker> <folder>    # use a different source folder
#
# Source (default): ~/Machinelab Dropbox/Matsuoka Daijiro/reference/<maker>
# State (in repo, gitignored):
#   keyence -> workspace/keyence-manuals    (legacy path, preserved)
#   <maker> -> workspace/<maker>-manuals
#     lib/text/<short>.txt   extracted, page-marked text
#     _MANIFEST.tsv          processed records (key = id + size)
#     STATUS.md              human-readable done/pending table
set -uo pipefail

MAKER="${1:?maker required (e.g. keyence|iai|oriental-motor)}"; shift || true
STATUS_ONLY=0
REF="$HOME/Machinelab Dropbox/Matsuoka Daijiro/reference"
FOLDER="$REF/$MAKER"
for a in "$@"; do
  case "$a" in
    --status) STATUS_ONLY=1 ;;
    *) FOLDER="$a" ;;
  esac
done

REPO="$HOME/claude-telegram-bot"
case "$MAKER" in
  keyence) BASE="$REPO/workspace/keyence-manuals" ;;   # legacy path
  *)       BASE="$REPO/workspace/${MAKER}-manuals" ;;
esac
TXT="$BASE/lib/text"; MAN="$BASE/_MANIFEST.tsv"; STATUS="$BASE/STATUS.md"
EXTRACT="$REPO/scripts/extract-keyence-manual.sh"
mkdir -p "$TXT"
[ -f "$MAN" ] || printf 'id\tsize\tpages\tlang\ttype\tdate\tshort\tfile\n' > "$MAN"

[ -d "$FOLDER" ] || { echo "ERROR: folder not found: $FOLDER" >&2; exit 1; }

# --- shortname / id / lang derivation, per maker ---
derive_keyence() { # <basename> -> "<type>_<model>_<lang>_<asidnum>"
  local f="$1"
  local asid; asid=$(echo "$f" | grep -oE 'AS_[0-9]+' | head -1)
  local lang=ja
  echo "$f" | grep -qE '_GB_|GB_WW|_EN_|_E\.pdf' && lang=en
  local type=other
  echo "$f" | grep -q '_RM_' && type=refmanual
  echo "$f" | grep -q '_UM_' && type=usermanual
  echo "$f" | grep -q '_TG_' && type=techguide
  local model; model=$(echo "$f" | grep -oiE 'KV-?[A-Za-z0-9]+' | head -1 | tr 'A-Z' 'a-z' | tr -d '-')
  [ -z "$model" ] && model=kv
  echo "${type}_${model}_${lang}_${asid#AS_}"
}
derive_generic() { # <basename> -> sanitized lowercase slug (grep target)
  local b="${1%.*}"
  echo "$b" | tr 'A-Z' 'a-z' | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//'
}
detect_lang_generic() { # trailing E=英 / J=日 (Oriental Motor) or _EN_/_GB_ tokens; default ja
  local b="${1%.*}"
  if echo "$b" | grep -qE '[0-9]E$'; then echo en
  elif echo "$b" | grep -qiE '_EN_|_GB_'; then echo en
  else echo ja; fi
}

new=0; skip=0; total=0
while IFS= read -r pdf; do
  total=$((total+1))
  base=$(basename "$pdf")
  size=$(stat -f %z "$pdf" 2>/dev/null)
  if [ "$MAKER" = "keyence" ]; then
    id=$(echo "$base" | grep -oE 'AS_[0-9]+' | head -1); id=${id:-NOID}
    short=$(derive_keyence "$base")
    lang=$(echo "$short" | grep -qE '_en_' && echo en || echo ja)
    type=$(echo "$short" | cut -d_ -f1)
  else
    short=$(derive_generic "$base"); id="$short"
    lang=$(detect_lang_generic "$base")
    type=other
  fi
  if grep -q "^${id}	${size}	" "$MAN" 2>/dev/null; then
    skip=$((skip+1)); continue
  fi
  if [ "$STATUS_ONLY" = "1" ]; then continue; fi
  echo ">> extracting: $base -> $short"
  if MANUAL_WS_BASE="$BASE" bash "$EXTRACT" "$pdf" lib "$short" >/dev/null 2>&1; then
    pages=$(pdfinfo "$pdf" 2>/dev/null | awk '/^Pages:/{print $2}'); pages=${pages:-?}
    today=$(date +%Y-%m-%d)
    printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$id" "$size" "$pages" "$lang" "$type" "$today" "$short" "$base" >> "$MAN"
    new=$((new+1))
  else
    echo "!! extract FAILED (scanned? run OCR manually): $base" >&2
  fi
done < <(find "$FOLDER" -iname '*.pdf' 2>/dev/null | sort)

# --- write STATUS.md: every PDF in folder + processed state ---
{
  echo "# ${MAKER} Manuals — Processing Status"
  echo "_source: \`$FOLDER\`  (auto-generated by sync-manuals.sh ${MAKER})_"
  echo
  echo "Grep text in \`workspace/$(basename "$BASE")/lib/text/<shortname>.txt\`.  Page markers: \`===== PAGE n =====\`."
  echo
  echo "| ✓ | id | type | lang | pages | shortname (grep target) | file |"
  echo "|---|----|------|------|-------|-------------------------|------|"
  while IFS= read -r pdf; do
    base=$(basename "$pdf")
    size=$(stat -f %z "$pdf" 2>/dev/null)
    if [ "$MAKER" = "keyence" ]; then
      id=$(echo "$base" | grep -oE 'AS_[0-9]+' | head -1); id=${id:-NOID}
    else
      id=$(derive_generic "$base")
    fi
    row=$(grep "^${id}	${size}	" "$MAN" 2>/dev/null | head -1)
    if [ -n "$row" ]; then
      pages=$(echo "$row" | cut -f3); lang=$(echo "$row" | cut -f4); type=$(echo "$row" | cut -f5); short=$(echo "$row" | cut -f7)
      printf '| ✅ | %s | %s | %s | %s | `%s` | %s |\n' "$id" "$type" "$lang" "$pages" "$short" "$base"
    else
      printf '| ⏳ | %s | — | — | — | (未処理) | %s |\n' "$id" "$base"
    fi
  done < <(find "$FOLDER" -iname '*.pdf' 2>/dev/null | sort)
  echo
  echo "_processed: $(( $(wc -l < "$MAN") - 1 )) record(s).  Run \`bash scripts/sync-manuals.sh ${MAKER}\` after adding PDFs._"
} > "$STATUS"

echo "---"
echo "maker: $MAKER | folder PDFs: $total | newly extracted: $new | already done: $skip"
echo "STATUS: $STATUS"
