/**
 * Darwin Engine v1.2.2 - Backup Generator
 *
 * Jarvis自身がバックアップとしてアイデアを生成
 * 2ノード以上失敗時に不足分を補填
 */

import type { DarwinThemeType } from './schema-validator';

export interface BackupIdeaRequest {
  theme: DarwinThemeType;
  count: number;
  failedModels: string[];
  existingIdeas: Array<{ title: string; theme: string }>;
}

export interface BackupIdea {
  title: string;
  content: string;
  rationale: string;
  isBackup: true;
  backupReason: string;
}

/**
 * Jarvis Backup Idea Generator
 */
export class BackupGenerator {
  /**
   * Generate backup ideas when models fail
   */
  async generate(request: BackupIdeaRequest): Promise<BackupIdea[]> {
    const ideas: BackupIdea[] = [];

    for (let i = 0; i < request.count; i++) {
      const idea = await this.generateSingleIdea(
        request.theme,
        request.existingIdeas,
        request.failedModels
      );
      ideas.push(idea);
    }

    return ideas;
  }

  /**
   * Generate single backup idea
   */
  private async generateSingleIdea(
    theme: DarwinThemeType,
    existingIdeas: Array<{ title: string; theme: string }>,
    failedModels: string[]
  ): Promise<BackupIdea> {
    // Template-based idea generation (deterministic fallback)
    const templates = this.getTemplatesForTheme(theme);

    if (templates.length === 0) {
      // Fallback if no templates available
      return {
        title: `Backup Idea for ${theme}`,
        content: `This is a backup idea generated after model failures.`,
        rationale: `Generated as fallback due to lack of templates.`,
        isBackup: true,
        backupReason: `Generated by Jarvis (backup) after ${failedModels.join(', ')} failed to respond`,
      };
    }

    const template = templates[Math.floor(Math.random() * templates.length)]!;

    // Ensure uniqueness against existing ideas
    let attempt = 0;
    let title = template.title;
    let content = template.content;
    let rationale = template.rationale;

    while (this.isDuplicate(title, existingIdeas) && attempt < 10) {
      title = this.mutateTitle(template.title, attempt);
      attempt++;
    }

    const backupReason = `Generated by Jarvis (backup) after ${failedModels.join(', ')} failed to respond`;

    return {
      title,
      content,
      rationale,
      isBackup: true,
      backupReason,
    };
  }

  /**
   * Get idea templates for theme
   */
  private getTemplatesForTheme(theme: DarwinThemeType): Array<{ title: string; content: string; rationale: string }> {
    const templates: Record<DarwinThemeType, Array<{ title: string; content: string; rationale: string }>> = {
      product: [
        {
          title: 'AI-Powered Customer Feedback Analyzer',
          content: 'Automatically analyze customer feedback from all channels (email, chat, social) using NLP to identify trends, sentiment, and actionable insights. Generate weekly reports highlighting top issues and opportunities.',
          rationale: 'Customer feedback is scattered across channels. Centralizing and analyzing it systematically can reveal patterns that manual review misses, leading to better product decisions.',
        },
        {
          title: 'Self-Service Product Tour Builder',
          content: 'Enable product managers to create interactive product tours without engineering resources. Drag-and-drop interface with conditional logic, user segmentation, and A/B testing built-in.',
          rationale: 'Product tours improve onboarding but require engineering time for each iteration. A self-service tool accelerates experimentation and reduces bottlenecks.',
        },
        {
          title: 'Feature Usage Heat Map Dashboard',
          content: 'Visual dashboard showing which features are used most/least by different user segments. Color-coded heat map with drill-down capability to see usage patterns over time.',
          rationale: 'Understanding feature adoption helps prioritize development and identify unused features that can be sunset or improved.',
        },
      ],
      marketing: [
        {
          title: 'Automated Social Proof Widget',
          content: 'Display real-time notifications of user signups, purchases, or achievements on website. Dynamically generated based on actual activity with privacy-preserving anonymization.',
          rationale: 'Social proof increases conversion rates by 15-30%. Automating this removes manual work and ensures always-fresh content.',
        },
        {
          title: 'Customer Story Video Generator',
          content: 'Template-based tool that creates customer success videos from interview transcripts. AI generates script, selects B-roll, adds captions, and produces publish-ready video in minutes.',
          rationale: 'Video testimonials are highly effective but expensive to produce. Automating 80% of the work makes them scalable.',
        },
        {
          title: 'Referral Program Gamification',
          content: 'Add game mechanics to referral program: levels, badges, leaderboards. Reward top referrers with exclusive perks. Monthly challenges with bonus rewards.',
          rationale: 'Gamification increases engagement by 40-50%. Makes referrals fun and competitive, driving higher participation.',
        },
      ],
      operations: [
        {
          title: 'Automated Invoice Processing Pipeline',
          content: 'OCR-based system that extracts data from invoices, matches to purchase orders, flags discrepancies, and routes for approval. 95% straight-through processing rate.',
          rationale: 'Manual invoice processing is error-prone and slow. Automation reduces processing time from days to hours and cuts errors by 80%.',
        },
        {
          title: 'Meeting Cost Calculator Dashboard',
          content: 'Real-time dashboard showing cost of ongoing meetings based on attendees\' salaries. Displays total cost and suggests optimal attendee list.',
          rationale: 'Meetings are invisible costs. Making costs visible encourages more efficient meetings and better attendee selection.',
        },
        {
          title: 'Predictive Maintenance Alert System',
          content: 'Monitor equipment telemetry and predict failures 2-4 weeks in advance. Schedule maintenance during low-usage periods to minimize downtime.',
          rationale: 'Reactive maintenance is 3x more expensive than predictive. Early warnings prevent catastrophic failures and optimize scheduling.',
        },
      ],
      strategy: [
        {
          title: 'Competitive Intelligence Dashboard',
          content: 'Aggregate competitor data from public sources: pricing changes, feature releases, hiring patterns, customer reviews. Weekly digest with strategic implications.',
          rationale: 'Competitive intelligence is scattered across sources. Centralizing it enables faster strategic responses and identifies market gaps.',
        },
        {
          title: 'OKR Dependency Mapping Tool',
          content: 'Visualize dependencies between teams\' OKRs. Identify critical paths, bottlenecks, and risks. Simulate impact of delays on downstream objectives.',
          rationale: 'OKRs exist in silos. Understanding dependencies prevents surprises and enables better cross-team coordination.',
        },
        {
          title: 'Market Entry Risk Assessment Framework',
          content: 'Structured framework for evaluating new market opportunities: TAM analysis, competitive landscape, regulatory risks, go-to-market costs. Generates risk-adjusted ROI projection.',
          rationale: 'Market entry decisions are high-stakes. A systematic framework reduces bias and ensures all critical factors are considered.',
        },
      ],
      culture: [
        {
          title: 'Anonymous Culture Pulse Survey',
          content: 'Weekly 3-question pulse survey measuring team morale, psychological safety, and workload. Anonymous responses with trend analysis and manager alerts for concerning patterns.',
          rationale: 'Culture issues fester when invisible. Regular pulse checks catch problems early before they cause attrition.',
        },
        {
          title: 'Cross-Functional Buddy Program',
          content: 'Randomly pair employees from different departments for monthly coffee chats. App suggests conversation starters and tracks participation.',
          rationale: 'Silos reduce collaboration and innovation. Cross-functional relationships break down barriers and spread knowledge.',
        },
        {
          title: 'Recognition Points Marketplace',
          content: 'Peer-to-peer recognition system with points that can be redeemed for rewards (gift cards, extra PTO, donations). Public leaderboard and monthly highlights.',
          rationale: 'Recognition boosts morale and retention. Peer recognition is more meaningful than top-down, and points add tangible value.',
        },
      ],
    };

    return templates[theme] || [];
  }

  /**
   * Check if title is duplicate
   */
  private isDuplicate(title: string, existingIdeas: Array<{ title: string; theme: string }>): boolean {
    const normalizedTitle = title.toLowerCase().trim();
    return existingIdeas.some(idea => idea.title.toLowerCase().trim() === normalizedTitle);
  }

  /**
   * Mutate title to create variation
   */
  private mutateTitle(title: string, attempt: number): string {
    const mutations = [
      (t: string) => `Enhanced ${t}`,
      (t: string) => `${t} v2.0`,
      (t: string) => `Next-Gen ${t}`,
      (t: string) => `Improved ${t}`,
      (t: string) => `${t} Pro`,
      (t: string) => `Advanced ${t}`,
      (t: string) => `${t} Plus`,
      (t: string) => `Smart ${t}`,
      (t: string) => `${t} Engine`,
      (t: string) => `Intelligent ${t}`,
    ];

    const mutation = mutations[attempt % mutations.length]!;
    return mutation(title);
  }

  /**
   * Calculate degraded mode severity
   */
  static getDegradedModeSeverity(failedModels: string[]): 'normal' | 'degraded' | 'critical' {
    const failedCount = failedModels.length;

    if (failedCount === 0) return 'normal';
    if (failedCount === 1) return 'degraded';
    return 'critical'; // 2+ failures
  }

  /**
   * Format backup report
   */
  static formatBackupReport(request: BackupIdeaRequest, generatedCount: number): string {
    const severity = BackupGenerator.getDegradedModeSeverity(request.failedModels);
    const icon = {
      normal: '✅',
      degraded: '⚠️',
      critical: '🚨',
    }[severity];

    return [
      `${icon} Backup Generator Activated`,
      `Severity: ${severity.toUpperCase()}`,
      `Failed models: ${request.failedModels.join(', ')}`,
      `Theme: ${request.theme}`,
      `Generated: ${generatedCount}/${request.count} backup ideas`,
    ].join('\n');
  }
}
